### ISSUE TITLE
User Research - IDEA

### ISSUE THREAD

**Issue by LaLeonie** [fac-17/Where-Should-We-Meet#1]
<img width="615" alt="Screenshot 2019-09-02 at 17 30 18" src="https://user-images.githubusercontent.com/45558475/64126878-6472fa00-cda7-11e9-9349-0e9a0625d097.png">
<img width="645" alt="Screenshot 2019-09-02 at 17 30 21" src="https://user-images.githubusercontent.com/45558475/64126882-65a42700-cda7-11e9-8629-bbdb565ce0d0.png">
<img width="717" alt="Screenshot 2019-09-02 at 17 30 27" src="https://user-images.githubusercontent.com/45558475/64126885-676dea80-cda7-11e9-9f5d-42d71de44e37.png">
<img width="666" alt="Screenshot 2019-09-02 at 17 31 22" src="https://user-images.githubusercontent.com/45558475/64126924-8a000380-cda7-11e9-8c31-7d309e61f3a2.png">
<img width="731" alt="Screenshot 2019-09-02 at 17 31 33" src="https://user-images.githubusercontent.com/45558475/64126927-8c625d80-cda7-11e9-9d7a-dc67bcb000f2.png">

**Comment by LaLeonie** [comment]
**What do you consider when making plans with friends?**

- Most users prioritize the convenience of location, followed by budget and quality of location 
- The length of travel time that users are willing to spend depends on the length of the meeting i.e. the longer the meeting, the longer users are willing to travel 
- another point of consideration is individual interests, such as events, prefered food, vibe etc.

**Comment by georgiamshaw** [comment]
**How do you plan your travel routes?**

- Google Maps: 10
- Citymapper: 12
-

**Comment by LaLeonie** [comment]
**Tell us about apps that you love and what you love about them**

_Popular apps_
Google maps, Citymapper, WhatsApp, Spotify, Mubi, Ryanair, BBC

_Popular features_
- Simplicity 
- Integrated/centralized functionalities
- Customization 
- Live updates
- Multiple options to select from (such as routes) 
- Offline use

**Conclusion**
Simplicity over multifunctionality. Users prefer integrated apps ("I like the Ryanair app because it assembles my search and bookings and boarding pass in once place")

**Comment by sarahyjja** [comment]
**6. What do you find frustrating about making social plans with friends?**


1 - Schedule coordination
2 - Agreeing on  a plan
3 - Cancellation
4 - Not knowing where there is events (not including alcohol)
5 - Not knowing new places
6 - Traveling for too long/too expensive without knowing if the place is good or not

**Comment by reubengt** [comment]
# How do you pick a location when making social plans
Popular Opinions
- something convenient for everyone, but the factors change based on who they're meeting
- depends on type of activity
- distance and time between all people should be similar
- usually a central location
- check eventbrite or unidays for events
- vote among all attending
-  someone said they prefer local businesses

**Comment by reubengt** [comment]
**Do you use online resources when making social plans**
- some people said no
- check reviews to decide what place to visit
- citymapper and google maps for route planning
Apps/websites for finding places and things to do
- timeout
- resident advisor
- bfi southbank schedule
- secretldn.com
- tripadviser
- eater.com
- londonist
The following apps to schedule
- evernote
- doodle polls
- whatsapp & other messaging apps
