### ISSUE TITLE
Sort out CSS

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/Where-Should-We-Meet#120]
organise css files into logical and clear order
put related things into flex boxes

**Comment by samjam48** [comment]
Nice work on keeping clean CSS conventions and separate files.

The title 'finalStyle' sounds like the other files were just things you used to test and this is the master file. Perhaps 'finalPageStyle' would be better or something.

Also maybe a 'normalise.css' file for general styles that apply across the whole app would help
