### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by sarahyjja** [fac-17/Where-Should-We-Meet#13]
Can we link the event to the calendar at this stage?
Maybe adding some logos in the design or just have a click on a word and it will propose outlook/iCal/GoogleCalendar
<img width="351" alt="Capture d’écran 2019-09-09 à 10 40 40" src="https://user-images.githubusercontent.com/44409053/64520548-4e58c280-d2ee-11e9-8bea-95dda7977949.png">

**Comment by georgiamshaw** [comment]
Add the ability for user to create an event in the calendar of their choice.
Think this is correct but not sure!
https://developers.google.com/calendar/quickstart/js
