### ISSUE TITLE
Convert postcode to longitude/latitude

### ISSUE THREAD

**Issue by reubengt** [fac-17/Where-Should-We-Meet#17]
We need to spend some time searching for libraries/apis that offer this, as building a solution for this from scratch would be too large a scope for us to undertake

Ideally, this service/library should be able to
1. accept two locations as input (coordinates?)
2. return a middle point (possibly already on a transport route?)

Since our app is looking to provide both venue and route suggestions after this step, we need to find something that will integrate well with those processes.

**Comment by sarahyjja** [comment]
PROJECT:
- 2 postcodes convert to longitude/latitude
- return 4 infos (long/lat) divide by 2
