### ISSUE TITLE
Add swipe gestures

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/Where-Should-We-Meet#19]
We will need:
- Swiping left
- Swiping right
- Tapping
- Scrolling up
- Scrolling down
...and perhaps other things, too.

Useful links: 
https://css-tricks.com/simple-swipe-with-vanilla-javascript/
https://haensel.pro/javascript/vanilla-javascript-swipe-gesture-detection
https://gist.github.com/SleepWalker/da5636b1abcbaff48c4d

---
- The logic is done in file swipe
- hardcode images
- have to be link to the venue API

**Comment by sarahyjja** [comment]
PROJECT
- do we keep the button?
- if not, find how to swap in JS
