### ISSUE TITLE
Venue API - link to venue.hbs

### ISSUE THREAD

**Issue by LaLeonie** [fac-17/Where-Should-We-Meet#24]
#19 => the swipe gesture is done but the images are hardcoded in venues.hbs

### Using handlebars logic, link here the venue API which will populate the venues.hbs file

Research API => DONE
- What's the best API to use? 
- What filter options does it provide for the "What do you want to do?" page? 
- What venue information does it give us? 
- How many requests are possible per day/minute? 
- API key necessary?

**Comment by sarahyjja** [comment]
- Yelp API for venues -> which info do we collect

APIKEY = sD0S57LmXay-FWRu4ZEfC5Gfd1Bswwj8J9o0M0JZD_c1HoY81wDMs-flNHYRCnuOKFkwMh3KYaiNbnop8SixyYeWVAfp2WYDjTO9j65NWQgDiK9xyJkAlHGextNvXXYx
