### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by sarahyjja** [fac-17/Where-Should-We-Meet#40]
### Remote and local databases:
- [x] Update scheme 

- [x] Set up Database/Tables

- [x] Set up getData for final page

- [x] Set up postData for form

- [x] create a test database (share the info for the .env file)

- [x] Set up variable on Heroku

- [x] Change database to include venue information 

- [x] Change tests to fit with new database

- [x] Amend final page to replace hardcoded variables

- [x] Add insertPost on venue page to add venue information to the table

- [x] Delete table content when user is going to homepage

![Database](https://user-images.githubusercontent.com/44409053/64731693-92f48180-d4d9-11e9-88d3-8dcfc7e2e28d.png)

https://www.google.com/search?q=how+to+be+a+qa&oq=how+to+be+a+qa&aqs=chrome..69i57j0l5.2570j0j9&sourceid=chrome&ie=UTF-8#kpvalbx=_AyN2XavPG464gQaOzIGwDw24

**Comment by LaLeonie** [comment]
TO DO's: 

- [ ] Set up database/tables

- [ ] Get last row from table user_a_input table on final page

- [ ] Post row from user form into user_a_input table
