### ISSUE TITLE
Midpoint calculation file

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/Where-Should-We-Meet#55]
- Research how to find a midpoint between two locations in London
- Create a file name midpoint.js
- The function take a lat/long (hardcode at the moment but will be taken from logic.js)

**Comment by sarahyjja** [comment]
- We console.log a postcodeA and a postcodeB as 2 objects in an array.
- The file midpoint.js has the logic to calculate the midpoint from an array of 2 objects.
